export const GET_FAVORITES = 'GET_FAVORITES';
export const POST_FAVORITES = "POST_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";
export const ADD_ITEM_TO_CHART = 'ADD_ITEM_TO_CHART';
export const DELETE_CHART = "DELETE_CHART";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ITEM_CART = "GET_ITEM_CART";

export const DELETE_CART = "DELETE_CART";
export const GET_CHART_2 = "GET_CHART_2";
export const GET_REVIEWS = "GET_REVIEWS";
export const SAVE_RATING_AND_COMMENT = "SAVE_RATING_AND_COMMENT";
export const SAVE_RATING_WEB = 'SAVE_RATING_WEB';

export const POST_NEW_PRODUCT = "POST_NEW_PRODUCT"
export const GET_CARDS = 'GET_CARDS';
export const FILTER_CARDS = 'FILTER_CARDS';
export const GET_SEARCH = 'GET_SEARCH';
export const SET_NAME_FILTER = 'SET_NAME_FILTER';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const ORDER_BY_RATE = 'ORDER_BY_RATE'

export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ORDERS_ID = "GET_ORDERS_ID"
export const MODIFICAR_USUARIO = "MODIFICAR_USUARIO"