export const GET_FAVORITES = 'GET_FAVORITES';
export const POST_FAVORITES = "POST_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";
export const ADD_ITEM_TO_CHART = 'ADD_ITEM_TO_CHART';
export const POST_NEW_PRODUCT = "POST_NEW_PRODUCT"