export const GET_FAVORITES = 'GET_FAVORITES';
export const POST_FAVORITES = "POST_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";
export const ADD_ITEM_TO_CHART = 'ADD_ITEM_TO_CHART';
export const GET_CARDS = 'GET_CARDS';
export const FILTER_CARDS = 'FILTER_CARDS';
export const GET_SEARCH = 'GET_SEARCH';
export const SET_NAME_FILTER = 'SET_NAME_FILTER';

